//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroniceDeviceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Desciption { get; set; }
        public string ImagePath { get; set; }
        public decimal ProductPrice { get; set; }
    }
}
